# Generated by Django 4.1.2 on 2022-11-21 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Категории')),
            ],
        ),
        migrations.RemoveField(
            model_name='chats',
            name='title',
        ),
        migrations.AddField(
            model_name='chats',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='chats',
            name='chat_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название чата'),
        ),
        migrations.AddField(
            model_name='chats',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.category'),
        ),
    ]
