# Generated by Django 4.1.2 on 2022-11-21 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_name', models.CharField(max_length=64, verbose_name='Название подписки')),
                ('subs_active', models.BooleanField(verbose_name='Статус подписки')),
                ('subs_time', models.DateTimeField(verbose_name='Дата подписки')),
                ('action', models.DurationField(verbose_name='Оставшееся время')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
    ]
