# Generated by Django 4.1.2 on 2022-11-24 07:54

from django.db import migrations
from chats.models import Chats


def populate_chats(apps, schema_editor):
    for i in range(10):
        Chats.objects.create(
            title =f"Title {i}",
            description =f"D escription {i}"
        )
    
    


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_category_remove_chats_title_chats_author_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_chats),
    ]
